### ISSUE TITLE
Broken anchors when header contains accents

### ISSUE THREAD

**Issue by michael-jeulinl** [rehypejs/rehype-slug#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.0.1

### Link to runnable example

https://codesandbox.io/embed/infallible-andras-d4td0g?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

```

import {rehype} from 'rehype'
import rehypeSlug from 'rehype-slug';
import toc from '@jsdevtools/rehype-toc';

const sourceHtml = `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>sandbox document</title>
  </head>
  <body>
    <h1>title efé</h1>
    <h2>title efé</h2>
    <p>lorem ipsum</p>
  </body>
</html>
`

async function main() {
  document.querySelector('#source').textContent = sourceHtml

  rehype()
    .use(rehypeSlug)
    .use(toc)
    .process(sourceHtml)
    .then((file) => {
      document.querySelector('#result').textContent = String(file)
    })
}

main().catch((error) => {
  document.querySelector('#error').textContent = error
})

```

### Expected behavior

Normalize the extracted header to avoid it having accent (that can not be handled properly).

### Actual behavior

Id is not normalized and cause broken anchor in association with rehype-toc.

### Runtime

Node v17, Node v16

### Package manager

npm 8, npm 7

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Which one is wrong? What's the actual and what's the expected?

**Comment by michael-jeulinl** [comment]
Both are containing accents:
`<a class="toc-link toc-link-h1" href="#title-efé">`
`<h1 id="title-efé">title efé</h1>`

According to the specification : https://url.spec.whatwg.org/#concept-url-fragment
An URL fragment is ASCII-only (no "international characters" accepted directly).

The link containing the anchor #title-efé is broken.

**Comment by wooorm** [comment]
> Both are containing accents

You should try this HTML out in a browser and observe that it works.

> According to the specification : [url.spec.whatwg.org/#concept-url-fragment](https://url.spec.whatwg.org/#concept-url-fragment)
> An URL fragment is ASCII-only (no "international characters" accepted directly).

You reference the `URL` spec, which defines `URL` objects, that spec does not define what values are allowed inside `href` on `a` in the HTML spec, nor how URLs work on the web.
Non-ASCII values are allowed in URLs, which you can observe by passing them to `URL`:

```js
(new URL('https://example.com/#🤷‍')).hash // #%F0%9F%A4%B7%E2%80%8D
```

^-- this shows that the `URL` class as you linked supports non-ASCII characters as input, and creates the ASCII-only `hash` you linked  with percent-encoding.

Practically too, in these projects we follow the algorithm that GitHub uses. GitHub uses those accents. If you feel that they’re horrible wrong, go take it up with them.

**Comment by iBobik** [comment]
I have the same issue - it generated this slug which does not work in Safari: "začneme-tou-prvn%C3%AD-otázkou-kdo-jsem"

Also here people mentioned similar issue in Firefox: https://github.com/nuxt/content/issues/835

So it is not OK to have this characters in URL.

**Comment by wooorm** [comment]
The problem is nuxt. The problem is not this package. This package does not generate links. Using the IDs generated here in a URL is fine.

**Comment by iBobik** [comment]
I tried to copy ID from the code and paste is in a address bar, so Nuxt
link have not been involved.


Honza Pobořil


16. 6. 2022 18:13:00, Titus ***@***.***> napsal:

**Comment by wooorm** [comment]
Please make a reproduction. And read the thread. I tried that, it worked.
