### ISSUE TITLE
add a new option to treat no-break spaces as whitespace (and yield dashes in their place)

### ISSUE THREAD

**Issue by revelt** [rehypejs/rehype-slug#16]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Sometimes we use no-break spaces (https://www.fileformat.info/info/unicode/char/00a0/index.htm), `\u00A0` to prevent [widow/orphan words](https://practicaltypography.com/widow-and-orphan-control.html).

Currently, GitHub headings slug calculation algorithm will not treat a "raw" no-break space as a whitespace ([proof](https://github.com/revelt/test/blob/main/README.md#this-is-the-secondheading)) and this package matches GitHub's algorithm.

This is not ideal.

### Solution

What if we introduced a new option (disabled by default) which instructs `rehype-slug` to treat "raw" no-break spaces `\u00A0` as whitespace, yielding dashes in the output?

Unit test:

```js
rehype()
  .data('settings', {fragment: true})
  .use(rehypeSlug, {
    prefix: 'test-',
    treatNbspAsSpace: true
  })
  .process(
    [
      '<section>',
      '  <h1>Lorem Ipsum Dolor Sit\u00A0Amet</h1>',
      '  <h2>dolor—sit—amet</h2>',
      '  <h3>consectetur &amp; adipisicing</h3>',
      '  <h4>elit</h4>',
      '  <h5>elit</h5>',
      '  <p>sed</p>',
      '</section>'
    ].join('\n'),
    (error, file) => {
      t.ifErr(error, 'shouldn’t throw')

      t.equal(
        String(file),
        [
          '<section>',
          '  <h1 id="test-lorem-ipsum-dolor-sit-amet">Lorem Ipsum Dolor Sit\u00A0Amet</h1>',
          '  <h2 id="test-dolorsitamet">dolor—sit—amet</h2>',
          '  <h3 id="test-consectetur--adipisicing">consectetur &#x26; adipisicing</h3>',
          '  <h4 id="test-elit">elit</h4>',
          '  <h5 id="test-elit-1">elit</h5>',
          '  <p>sed</p>',
          '</section>'
        ].join('\n'),
        'should match'
      )
    }
  )
```

### Alternatives

Not really. We can keep status quo but that makes the life harder when trying to tackle the orphan word control in MDX.

**Comment by wooorm** [comment]
Hi there!

I don’t think this is a good idea: I think it’s very useful to push one slug algorithm instead. This helps everyone in the end. For example, in VS Code you can autocomplete links to headings, which will use the same algorithm that we do.

There are some really good other slugging algorithms, some with lots of options. I don’t think it’s a good idea to add every option someone might ever want here.

> Alternatives

I think there’s a very good alternative: this plugin is tiny! [15 lines](https://github.com/rehypejs/rehype-slug/blob/main/index.js). You can choose any slugging you want by writing your own plugins!

> This is not ideal.

> that makes the life harder when trying to tackle the orphan word control in MDX

What weird statements. This is open sources. This is programming. It’s about trade offs. You have different ones than other people.

---

For more info, see:
- https://github.com/remarkjs/remark-slug/issues?q=sort%3Aupdated-desc+is%3Aclosed+
- https://github.com/rehypejs/rehype-slug/pulls?q=sort%3Aupdated-desc+is%3Aclosed
- https://github.com/Flet/github-slugger/issues?q=sort%3Aupdated-desc+is%3Aclosed+
