### ISSUE TITLE
Option to capitalize slugs

### ISSUE THREAD

**Issue by bennycode** [rehypejs/rehype-slug#19]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently the only option provided by the plugin is a `prefix`. It would be nice to add further options so slugs can be written in capital letters. It would be also cool if a transformer could be defined to modify the generated slugs yourself.

### Solution

Adding a "capitalize" option or adding a callback where developers can defined their own slug customizations.

### Alternatives

Only by writing your own slug plugin.

**Comment by wooorm** [comment]
Hey! This project is intentionally simple. So that everyone uses the same slugs. It follows GitHub. So that what you write in markdown will work here. And in VS Code. In as many places.

The goal is to not add other options. It would go against the goal of everyone using the same slugs. The alternative, writing your own plugin, is fine! We recommend learning about ASTs, and this is a good example how to learn about them.

**Comment by bennycode** [comment]
Thanks for your explanation. I really like the idea of creating slugs similar to how GitHub does it, and I want to use this in my projects.

I am building an Astro blog, and I need to make sure it supports some links from an older blogging system. In that older system, some of the links are like `#TS2003`, but the plugin changes them to `#ts2003`. I can't update the old content, so how can I fix this and change the way the slug is created by the `rehype-slug` plugin? I was thinking about building my own transformer that under-the-hood calls `rehype-slug` and then just runs the `toUpperCase` on top of it?

Also, I'm wondering if there's a way to choose which heading levels get slugs/IDs. For example, I only want IDs for H2 headings and not for H3 headings. Is there a way to do that?

**Comment by wooorm** [comment]
I recommend changing the content.

See the source: https://github.com/rehypejs/rehype-slug/blob/main/lib/index.js.
Copy/paste it, remove what you don’t need, change it to do what you want.

`toUpperCase` makes everything uppercase, you probably don’t want that.

`headingRank(node)` returns `1`, `2`, etc for headings. Return for `1` if you don’t want `h1`.

**Comment by bennycode** [comment]
I appreciate your input. I will try to gradually transition to the new slug structure. For now, I'm using JavaScript within my Astro pages to convert incoming legacy slugs (capitalized in my case) into the new format.

Example:

```js
<script>
  (() => {
    const matchTS = /TS\d+/g;
    const hash = window.location.hash;
    const matches = hash.match(matchTS);
    if (matches) {
      window.location.hash = hash.replace('TS', 'ts');
    }
  })();
</script>
```
