### ISSUE TITLE
Typescript typings for this plugin

### ISSUE THREAD

**Issue by ChristianIvicevic** [rehypejs/rehype-slug#4]
Unlike many other plugins in the unified/remark/rehype ecosystem this one unfortunately doesn't provide Typescript typings. It would be nice if they could be provided, even though they will end up pretty short with only one exported function.

**Comment by ChristianMurphy** [comment]
A PR is welcome!
Unified has over 300 repos, we've been adding typings to many, but haven't gotten to this one yet.
If you'd be interested, https://github.com/rehypejs/rehype-document/pull/9/files is a good starting point for seeing the patterns we use in unified (checking with dtslint, using a folder named types, etc).

**Comment by ChristianIvicevic** [comment]
@ChristianMurphy The respective PR is ready for review, I am currently looking into `rehype-autolink-headings` as well since I need both plugins myself right now :)

**Comment by ChristianMurphy** [comment]
Thanks @ChristianIvicevic! :bow:
