### ISSUE TITLE
Add support for 'German' umlaute

### ISSUE THREAD

**Issue by tonprince** [rehypejs/rehype-slug#8]
I have an issue with german "umlaute" like ü, ö and ä, ẞ in slugs, the ids added to headings includes those. To have less problems with browser support they should be translated into ae, oe, ue or ss.

**Comment by ChristianMurphy** [comment]
Github slugger generates the slug
https://github.com/rehypejs/rehype-slug/blob/08bee08c89aa57270086a0ea60cd0e712760d211/package.json#L32
Automatically picks up new features and fixes from upstream, this would be addressed by https://github.com/Flet/github-slugger/issues/37

**Comment by wooorm** [comment]
This project follows GitHub, which does not change the diaeresis (those two dots) into other letters.
We also live in a unicode world, where URLs and HTML all support them well, so I don’t see a reason to change them?
