### ISSUE TITLE
Customize which headings are included

### ISSUE THREAD

**Issue by MauricioRobayo** [rehypejs/rehype-slug#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

There is no way to control to which headings an id will be added. 

### Solution

Enable an option to customize which headings are included (defaults to h1 - h6), like how [toc](https://github.com/JS-DevTools/rehype-toc#usage) handles it:

```js
rehype()
  .data('settings', {fragment: true})
  .use(slug, {
    headings: ["h2", "h3", "h4", "h5", "h6"],     // Exclude adding id to <h1>,
  })
  .process(buf)
  .then((file) => {
    console.log(String(file))
  })
```

### Alternatives

The option could also be added to [rehype-autolink-headings](https://github.com/rehypejs/rehype-autolink-headings), but if done here it will work on autolink as it will not autolink headings without ids.

**Comment by wooorm** [comment]
I’m open to a PR adding a `test` like this one: https://github.com/rehypejs/rehype-autolink-headings/commit/da79faca7cad13f08149840eb0c3913b375fdc94.

**Comment by wooorm** [comment]
Btw, I recommend you use that `test` in `rehype-autolink-headings`.
You can have nice link-to-self things for certain big headings only. While all other headings can also be linked to.
